Box Plot and Geographic Figures
6759-Project/cnn-downscaling pull request #5
Opened 2022-04-15 21:02 UTC by hemanthsheetha

Pushed the code for producing box plot and geographic figures. Let me know if there are any changes and we need to adjust the scales of geographic figures for better comparison. I tried to scale the figures but I think they can be scaled better.

2022-04-17 18:43 UTC, JakeColor requested changes
The biggest problem here is the mystery of the extreme errors in our bilinear interpolation [top] and normalizing flow [bottom] correlations:
![image](https://user-images.githubusercontent.com/6565064/163728094-5547cc76-8c2e-4107-a109-c10fabcd000f.png)

![image](https://user-images.githubusercontent.com/6565064/163728367-c4a403dd-073e-449b-81dc-6074816269d4.png)


It'd also be great if we could do MSE by geography
 

## Formatting/Details
As mentioned on Discord, can you please remove the many data files in this PR (just add .csv, .ckpt, .zarr, etc. to the .gitignore)? i'd like to keep the repo clean of data files

### boxplots.ipynb

- [x] Can you please place a horizontal red line at the ideal marks for bias (0.0) and stability (1.0)? 
- [x] - Remove `sns.set_theme(style='darkgrid')` to make way for `plt.style.use('seaborn-pastel')` we agreed on earlier
- [x] - `bias_mean`, `bias_p02`, `bias_p98`  axis label need to be changed to be consistent with previous plots: new label "Bias (°C)"
- [x] - similar: rename "corr" axis label to "Correlation"
- [x] - similar: "stability" to "Stability"
- [x] - your `width` argument does not match across plots 

### evaluation.ipynb

- [ ] - `vmin/vmax` do not match across across the geographic bias plots, which is important for comparability -- **let's use (-10,10) to capture the bias range across all models**

2022-04-18 19:29 UTC, oethier commented
Those are all good comments @JakeColor. One thing I would add though is switching the diverging colormap to a sequential one for the metrics where the middle value (white here) doesn't mean anything precise. We saw this in Alex's lecture on figures early this semester.

- [x] switch to a sequential color palette for correlation, stability and mse

2022-04-18 20:16 UTC, hemanthsheetha commented
Addressed almost all of the comments in the recent push

2022-04-18 20:28 UTC, JakeColor approved these changes

2022-04-18 20:32 UTC, merged